---
title: "Chap 7- Example"
format: html
editor: visual
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
## Se usar RMarkdown
# knitr::knit_engires$set(python = reticulate::eng_python)
```
```{r, setup-py}
#| include: false
#| 
library(reticulate)
## Se tiver problema criando o venv, rodar: python3 -m pip install virtualenv
virtualenv_create("py-r-bilinguist")
py_install(c("seaborn", "scikit-learn", "pandas", "numpy"), envname = "py-r-bilinguist")
use_virtualenv("py-r-bilinguist", required = TRUE)
reticulate::py_discover_config()

## R libs
library(dplyr)
library(ggplot2)
library(RSQLite)
library(DBI)
```

## Lendo os dados

```{r}
con <- dbConnect(SQLite(), "data/FPA_FOD_20170508.sqlite")
dbListTables(con)

df_fires <- dbGetQuery(con, "
                       SELECT STAT_CAUSE_DESCR, OWNER_CODE, DISCOVERY_DOY, 
                       FIRE_SIZE, LATITUDE, LONGITUDE
                       FROM Fires
                       WHERE (FIRE_YEAR=2015 AND STATE != 'AK' AND STATE != 'HI');")

dbDisconnect(con)
dim(df_fires)

df_fires <- df_fires |> 
  janitor::clean_names()

glimpse(df_fires)

map_plot <- ggplot(df_fires, aes(x = longitude, y = latitude, size = fire_size,
                                 color = factor(owner_code))) +
  geom_point(alpha = 0.15, shape = 16) +
  scale_size(range = c(0.5, 10)) +
  theme_classic() +
  theme(legend.position = "bottom",
        panel.background = element_rect(fill = "gray10"),
        
  )
map_plot
```

